const { test, expect } = require('@playwright/test');
const { ai } = require('@zerostep/playwright');

/**
 * ============================================================================
 * ADVANCED CONCEPT: SHIFT-LEFT AGENTIC TEST GENERATION (TDD)
 * ============================================================================
 * 
 * In a traditional SDLC, QA engineers write test scripts *after* developers
 * have built the UI. This creates a bottleneck.
 * 
 * With True AI Agents, we can achieve true "Shift-Left" testing.
 * 
 * How it works:
 * 1. A Product Manager writes a Jira Ticket with Acceptance Criteria.
 * 2. An LLM reads the Jira ticket and automatically generates this Playwright 
 *    script containing natural language `ai()` commands.
 * 3. This script is committed to the repo *before* the developers write any code.
 * 4. As the developer builds the UI, they run this script. Once it passes, 
 *    they know their feature meets the business requirements perfectly.
 */

test.describe('Shift-Left Agentic TDD Demonstration', () => {
    
    // Imagine this script was auto-generated by an AI reading this Jira ticket:
    // "JIRA-1024: As a user, I want to calculate my loan eligibility so I know my limit."
    // "Acceptance Criteria: Given a loan of 50000, tenure 10, income 5000, 
    //  When calculated, Then it should be Pre-Approved."

    test('Auto-generated test from Jira Acceptance Criteria', async ({ page }) => {
        if (!process.env.ZEROSTEP_TOKEN) {
            test.skip();
            return;
        }

        // Developer points the test to their local dev environment
        await page.goto('http://localhost:3000'); // Developer's local server (mocked)

        console.log("Executing auto-generated Agentic TDD script...");

        // The AI generated these steps entirely from the Jira criteria.
        // Notice how it doesn't need to know the IDs or Classes the developer 
        // hasn't even written yet.
        await ai('Enter 50000 into the requested loan amount field', { page, test });
        await ai('Enter 10 into the tenure field', { page, test });
        await ai('Enter 5000 into the monthly income field', { page, test });
        
        await ai('Click the calculate eligibility button', { page, test });

        const isApproved = await ai('Is the eligibility status showing as Pre-Approved?', { page, test });
        expect(isApproved).toBe(true);

        console.log("Feature complete! The developer has successfully fulfilled the Jira criteria.");
    });
});
